### ISSUE TITLE
Suggestion - Raw modules - Slightly less powerful

### ISSUE THREAD

**Issue by cengbrecht** [UberWaffe/ScienceCostTweaker#5]
Hey UberWaffe!
I was thinking about the RAW modules, and if we add all those extra modules to the one module, it should degrade the max power of the raw module. 
ie. RAW Speed module doesn't emit any pollution, or add extra power needs but it should always be slightly weaker than the speed module of the same level.
Just a thought. :)

**Comment by cengbrecht** [comment]
It's too bad you couldn't have a random value of potential loss applied to the raw modules at the creation of the map.
ie. a 1-6% drop in the max power of a raw module verses the original power of the non-raw mod.

**Comment by UberWaffe** [comment]
@cengbrecht The RAW modules are added by Bob's Mods, not by ScienceCostTweaker. The forum thread for it can be found [here](http://www.factorioforums.com/forum/viewtopic.php?f=51&t=4896).

:)

Science cost tweaker only adjusts the science pack cost of Bob's Mods research.
The only items from Bob's Mods it changes is the new laboratories that Bob's Mods adds.
